services:
  cherry:
    image: toanbk/nexus-prover:latest
    volumes:
      - ${WALLET_DIR}/n001:/wallet
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - ENDPOINT_URL=${ENDPOINT_URL}
      - no_proxy=${NO_PROXY}
      - NO_PROXY=${NO_PROXY}
    restart: always
    